version: '3.8'

networks:
  redisn:
    driver: bridge
    name: redisn

services:
  redis1:
    image: bitnami/redis:latest
    restart: always
    container_name: redis-server-1
    command: >
      /opt/bitnami/scripts/redis/run.sh --cluster-enabled no
      --appendonly yes
      --port 6379
      --maxmemory 256mb
      --maxmemory-policy allkeys-random
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
      - "16379:16379"
    volumes:
      - redis_data_1:/bitnami/redis/data
    networks:
      - redisn

  redis2:
    image: bitnami/redis:latest
    restart: always
    container_name: redis-server-2
    command: >
      /opt/bitnami/scripts/redis/run.sh --cluster-enabled no
      --appendonly yes
      --port 6379
      --maxmemory 256mb
      --maxmemory-policy allkeys-random
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6380:6379"
      - "16380:16379"
    volumes:
      - redis_data_2:/bitnami/redis/data
    networks:
      - redisn

  redis3:
    image: bitnami/redis:latest
    restart: always
    container_name: redis-server-3
    command: >
      /opt/bitnami/scripts/redis/run.sh --cluster-enabled no
      --appendonly yes
      --port 6379
      --maxmemory 256mb
      --maxmemory-policy allkeys-random
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6381:6379"
      - "16381:16379"
    volumes:
      - redis_data_3:/bitnami/redis/data
    networks:
      - redisn

  redis4:
    image: bitnami/redis:latest
    restart: always
    container_name: redis-server-4
    command: >
      /opt/bitnami/scripts/redis/run.sh --cluster-enabled no
      --appendonly yes
      --port 6379
      --maxmemory 256mb
      --maxmemory-policy allkeys-random
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6382:6379"
      - "16382:16379"
    volumes:
      - redis_data_4:/bitnami/redis/data
    networks:
      - redisn

  redis5:
    image: bitnami/redis:latest
    restart: always
    container_name: redis-server-5
    command: >
      /opt/bitnami/scripts/redis/run.sh --cluster-enabled no
      --appendonly yes
      --port 6379
      --maxmemory 256mb
      --maxmemory-policy allkeys-random
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6383:6379"
      - "16383:16379"
    volumes:
      - redis_data_5:/bitnami/redis/data
    networks:
      - redisn

  redis6:
    image: bitnami/redis:latest
    restart: always
    container_name: redis-server-6
    command: >
      /opt/bitnami/scripts/redis/run.sh --cluster-enabled no
      --appendonly yes
      --port 6379
      --maxmemory 256mb
      --maxmemory-policy allkeys-random
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6384:6379"
      - "16384:16379"
    volumes:
      - redis_data_6:/bitnami/redis/data
    networks:
      - redisn

  redis7:
    image: bitnami/redis:latest
    restart: always
    container_name: redis-server-7
    command: >
      /opt/bitnami/scripts/redis/run.sh --cluster-enabled no
      --appendonly yes
      --port 6379
      --maxmemory 256mb
      --maxmemory-policy allkeys-random
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6385:6379"
      - "16385:16379"
    volumes:
      - redis_data_7:/bitnami/redis/data
    networks:
      - redisn

  redis8:
    image: bitnami/redis:latest
    restart: always
    container_name: redis-server-8
    command: >
      /opt/bitnami/scripts/redis/run.sh --cluster-enabled no
      --appendonly yes
      --port 6379
      --maxmemory 256mb
      --maxmemory-policy allkeys-random
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6386:6379"
      - "16386:16379"
    volumes:
      - redis_data_8:/bitnami/redis/data
    networks:
      - redisn

  redisinsight:
    image: redislabs/redisinsight:latest
    restart: always
    container_name: redis-insight
    volumes:
      - redis-insight:/data
    ports:
      - "5540:5540"
    networks:
      - redisn
    depends_on:
      - redis1
      - redis2
      - redis3
      - redis4
      - redis5
      - redis6
      - redis7
      - redis8

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - REDIS_NODES=redis-server-1:6379,redis-server-2:6379,redis-server-3:6379,redis-server-4:6379,redis-server-5:6379,redis-server-6:6379,redis-server-7:6379,redis-server-8:6379
    container_name: api-container
    ports:
      - "5001:5001"
    networks:
      - redisn
    depends_on:
      - redis1
      - redis2
      - redis3
      - redis4
      - redis5
      - redis6
      - redis7
      - redis8

  grpc-server:
    build:
      context: .
      dockerfile: Dockerfile.grpc
    container_name: grpc-server-container
    ports:
      - "50051:50051"
    networks:
      - redisn
    dns:
      - 8.8.8.8 

volumes:
  redis_data_1:
    driver: local
  redis_data_2:
    driver: local
  redis_data_3:
    driver: local
  redis_data_4:
    driver: local
  redis_data_5:
    driver: local
  redis_data_6:
    driver: local
  redis_data_7:
    driver: local
  redis_data_8:
    driver: local
  redis-insight:
    driver: local
