# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dns_pb2 as dns__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dns_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DNSServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDNS = channel.unary_unary(
                '/dns.DNSService/GetDNS',
                request_serializer=dns__pb2.DNSRequest.SerializeToString,
                response_deserializer=dns__pb2.DNSResponse.FromString,
                _registered_method=True)


class DNSServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDNS(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DNSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDNS': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDNS,
                    request_deserializer=dns__pb2.DNSRequest.FromString,
                    response_serializer=dns__pb2.DNSResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dns.DNSService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dns.DNSService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DNSService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDNS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dns.DNSService/GetDNS',
            dns__pb2.DNSRequest.SerializeToString,
            dns__pb2.DNSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
